### ISSUE TITLE
Failed to set permissions for directory '/tmp/s3_downloads': permission denied

### ISSUE THREAD

**Issue by maurosc3ner** [degauss-org/nlcd#8]
Hi,

I am getting the segmentation fault when running this image:
$docker run --rm -v $PWD:/tmp ghcr.io/degauss-org/nlcd myfile.csv

![image](https://github.com/degauss-org/nlcd/assets/4038971/69ffce16-81ca-4889-aba3-8ad19f49f5a2)

**Additional notes:**
All other images (geocoder, deprivation, greenspace, and aadt) run without issues.
Platform: Apple macbook pro M1 Max 64 GB
OS: Monterey 12.6.5
Docker: latest (v4.27.2)

Thanks

**Comment by cole-brokamp** [comment]
Can you try making a directory called `s3_downloads` first and see if the same error appears?

I think there is a conflict happening here because the container is using the s3 package to download files to the `/tmp` directory, which is also the directory we are using to specify the input csv file.

The s3 package downloads files to the package data directory (`tools::R_user_dir("s3", "data")`), which is platform dependent.  On ubuntu, which the docker images runs, this is `/home/user/.local/share/R/s3`.

You can also try to pass the `R_USER_DATA_DIR` environment variable to a different location, like `/tmp/s3_downloads` and see if it will use the created `s3_downloads` directory.

Lastly, maybe look and check if the docker desktop host has proper permissions to access all of the folders on your hard drive.
